pipeline{
    agent {
        label 'slave-1'
    }
    environment {
        CON_NAME = 'react-con'
        IMG_NAME = 'sanjai:v1'
    }
    stages{
        stage('Build'){
            steps{
                script{
                    sh 'sudo su'
                    sh 'sudo docker stop ${CON_NAME}'
                    sh 'sudo docker rm -f ${CON_NAME}'
                    sh 'sudo docker rmi ${IMG_NAME}'
                    sh 'bash build.sh'
                    
                                   }
            }

        }
        stage('Deploy'){
            steps{
                script{
                    sh 'bash deploy.sh'

                }
            }
        }
    }
}
