@Library('Libraries@main') _
pipeline{
    //agent any
    agent {
        label 'slave-1'
    }
    //parameters {choice (choices : ['dev' , 'qa' , 'staging' , 'prod'],description : 'Choose dev or qa or staging or prod',name : 'ENV')
    environment {
        CON_NAME = 'react-con'
        IMG_NAME = 'sanjai:v1'
        PROJECT_NAME = 'Demo_repo'
        Env_name = 'dev'
        Version = 'latest'
    }
    stages{
        stage('Build'){
            steps{
                script{
                    sh 'sudo su'
                    sh 'sudo docker stop ${CON_NAME}'
                    sh 'sudo docker rm -f ${CON_NAME}'
                    sh 'sudo docker rmi ${IMG_NAME}'
                    sh 'cd react-app ; bash build.sh'
                    sh "tar -zcvf node_modules.tar.gz"
                    
                                   }
            }

        }
        stage('Deploy'){
            steps{
                script{
                    sh 'cd react-app ; bash deploy.sh'

                }
            }
        }
        stage ('Push to Artifactory') {
               steps {
                   script {        
                        pattern = "node_modules.tar.gz"
                        target = "${PROJECT_NAME}/latest/${params.ENVIRONMENT}/${PROJECT_NAME}.tar.gz"
                        Push_to_Artifactory(["$pat","$tar"])
                    }
                }
            }

    }
}
