pipeline {
    agent {
        label 'slave-1'
    }
    environment {
        CON_NAME = 'nginx-cont-1'
        IMG_NAME = 'nginx:latest'
    }
       stages {
         stage('Build image') {
             steps {
                 sh 'sudo su'
                 sh 'sudo docker pull ${IMG_NAME}'
                 sh 'sudo docker run -d -p 80:80 --name ${CON_NAME} ${IMG_NAME}'
                 sh 'sudo docker ps -a'
             }
         }
        stage('Update-nginx') {
            steps {
                sh 'cp /home/ubuntu/workspace/Test-job-2/update-nginx/index.html ${CON_NAME}:/usr/share/nginx/html'
            }
        }
}
}
